# Generated by Django 4.2.7 on 2025-09-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_assignment_question_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuserimport',
            name='file',
            field=models.FileField(help_text='<a href="/admin/portal/bulkuserimport/download-template/?user_type=student" class="button" style="margin-bottom:1em;margin-top:0.5em;display:inline-block;" target="_blank">Download Student Import CSV Template</a>', upload_to='bulk_imports/'),
        ),
    ]
