# Generated by Django 4.2.7 on 2025-09-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_bulkuserimport_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuserimport',
            name='file',
            field=models.FileField(help_text='\n                                <a href="/admin/portal/bulkuserimport/download-template/?user_type=student"\n                                class="button"\n                                style="margin-bottom:1em;margin-top:0.5em;display:inline-block;"\n                                target="_blank">Download Student Template</a>\n                                <a href="/admin/portal/bulkuserimport/download-template/?user_type=teacher"\n                                class="button"\n                                style="margin-bottom:1em;margin-left:0.5em;display:inline-block;"\n                                target="_blank">Download Teacher Template</a>\n                                ', upload_to='bulk_imports/'),
        ),
    ]
