# Generated by Django 4.2.7 on 2025-09-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
