# Generated by Django 4.2.7 on 2025-09-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.CharField(blank=True, default='LH 5, 3rd Floor', max_length=20),
        ),
    ]
